version: '3.8'
services:
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    # за локално тестване не са необходими deploy
    deploy:
      resources: 
        reservations:
          cpus: '2'
          memory: 2GB
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=myStrongPassword12#
    volumes:
      - sqldata:/var/opt/mssql/server
  web-app:
    container_name: web-app
    # за локално тестване
    # build: 
    #   dockerfile: ./Dockerfile
    image: spasina00bazarscr.azurecr.io/bazars
    # от изискванията - не е за локалното тестване
    domainname: spasina00-bazars
    ports:
      - "80:80"
    restart: on-failure

volumes:
  sqldata:
  # тук надолу всичко е за AZURE, а не за локалното тестване
    driver: azure_file
    driver_opts:
      share_name: sql-volume
      storage_account_name: spasina00bazarsa